# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/debian-7.8-32-nocm"
  config.vm.synced_folder ENV['STACK_BUILD_DIR'], "/vagrant-build", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y net-tools wget zlib1g-dev ruby-dev libgmp-dev lsb-release ca-certificates git libtinfo-dev
    curl -sSL https://www.stackage.org/stack/linux-i386 \
      | tar xzvf - --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
    chmod a+x /usr/local/bin/stack
    if ! which fpm; then
      apt-get install -y ruby-dev libffi-dev make build-essential
      apt-get install -y rubygems || true
      gem install json --version '< 1.8.0'
      gem install fpm --version '< 1.4.0'
    fi
    if ! which deb-s3; then
      gem install deb-s3
    fi
    if ! which aws; then
      apt-get install -y python2.7
      curl -O https://bootstrap.pypa.io/get-pip.py
      sudo python2.7 get-pip.py
      sudo pip install awscli
    fi
  SHELL
end
