name: rio
version: 0.0.0.0
synopsis: A standard library for Haskell
description: Work in progress library, see README at <https://github.com/commercialhaskell/stack/tree/rio/subs/rio#readme>
license: MIT
author: Michael Snoyman
maintainer: michael@snoyman.com
category: Control
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base < 10
- bytestring
- containers
- deepseq
- directory
- exceptions # FIXME what do we do with MonadThrow?
- filepath
- hashable
- microlens
- mtl
- text
- time
- typed-process >= 0.2.1.0
- unliftio >= 0.2.4.0
- unordered-containers
- vector

when:
- condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src/
  other-modules:
  - RIO.Prelude
