#!/usr/bin/env expect

set timeout 20

spawn gpg --edit-key test

expect "gpg>"                                                        { send "trust\r" }
expect "Your decision?"                                              { send "5\r" }
expect "Do you really want to set this key to ultimate trust? (y/N)" { send "y\r" }
expect "gpg>"                                                        { send "save\r" }

interact
