name:                stack
version:             1.0.5
synopsis:            The Haskell Tool Stack
description: |
  Please see the README.md for usage information, and
  the wiki on Github for more details.  Also, note that
  the API for the library is not currently stable, and may
  change significantly, even between minor releases. It is
  currently only intended for use by the executable.
license:             BSD3
author:              Commercial Haskell SIG
maintainer:          manny@fpcomplete.com
category:            Development
homepage:            http://haskellstack.org

github: commercialhaskell/stack

extra-source-files:
  - ChangeLog.md
  - CONTRIBUTING.md
  - README.md
  - stack.yaml
  - test/package-dump/*.txt

flags:
  integration-tests:
    manual: True
    default: False
    description: Run the integration test suite

  disable-git-info:
    manual: True
    default: False
    description: Disable compile-time inclusion of current git info in stack
    # Disabling git info can lead to a quicker workflow in certain scenarios
    # when you're developing on stack itself, but should otherwise be avoided
    # see: https://github.com/commercialhaskell/stack/issues/1425

  static:
    manual: True
    default: False
    description: Pass -static/-pthread to ghc when linking the stack binary.
    # Not intended for general use. Simply makes it easier to build a fully
    # static binary on Linux platforms that enable it.

ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-uni-patterns -fwarn-incomplete-record-updates

when:
  condition: os(windows)
  then:
    cpp-options: -DWINDOWS
    dependencies: Win32
  else:
    dependencies: unix >= 2.7.0.1

library:
  source-dirs: src
  dependencies:
    - Cabal >= 1.18.1.5
    - aeson (>= 0.8.0.2 && < 0.10) || (>= 0.11 && < 0.12)
    - ansi-terminal >= 0.6.2.3
    - async >= 2.0.2 && < 2.2
    - attoparsec >= 0.12.1.5 && < 0.14
    - base >= 4.7 && <5
    - base16-bytestring
    - base64-bytestring
    - binary >= 0.7
    - binary-tagged >= 0.1.1
    - blaze-builder
    - byteable
    - bytestring
    - conduit >= 1.2.4
    - conduit-extra >= 1.1.7.1
    - containers >= 0.5.5.1
    - cryptohash >= 0.11.6
    - cryptohash-conduit
    - directory >= 1.2.1.0
    - edit-distance >= 0.2
    - either
    - enclosed-exceptions
    - errors < 2.2
    - exceptions >= 0.8.0.2
    - extra
    - fast-logger >= 2.3.1
    - filelock >= 0.1.0.1
    - filepath >= 1.3.0.2
    - fsnotify >= 0.2.1
    - hashable >= 1.2.3.2
    - hpc
    - http-client >= 0.4.17
    - http-client-tls >= 0.2.2
    - http-conduit >= 2.1.7
    - http-types >= 0.8.6 && < 0.10
    - lifted-base
    - microlens >= 0.3.0.0
    - monad-control
    - monad-logger >= 0.3.13.1
    - mtl >= 2.1.3.1
    - optparse-applicative >= 0.11 && < 0.13
    - path >= 0.5.1
    - path-io >= 1.0.0 && < 2.0.0
    - persistent >= 2.1.2
    - persistent-sqlite >= 2.1.4
    - persistent-template >= 2.1.1
    - pretty >= 1.1.1.1
    - process >= 1.2.0.0
    - resourcet >= 1.1.4.1
    - retry >= 0.6 && < 0.8
    - safe >= 0.3
    - semigroups >= 0.5 && < 0.19
    - split
    - stm >= 2.4.4
    - streaming-commons >= 0.1.10.0
    - tar >= 0.4.1.0 && < 0.6
    - template-haskell >= 2.9.0.0
    - temporary >= 1.2.0.3
    - text >= 1.2.0.4
    - text-binary
    - time >= 1.4.2
    - transformers >= 0.3.0.0
    - transformers-base >= 0.4.4
    - unix-compat
    - unordered-containers >= 0.2.5.1
    - vector >= 0.10.12.3 && < 0.12
    - vector-binary-instances
    - yaml >= 0.8.10.1
    - zlib >= 0.5.4.2 && < 0.7
    - deepseq >= 1.4
    - hastache
    - project-template >= 0.2
    - uuid
    - zip-archive
    - hpack >= 0.10.0

executables:
  stack:
    source-dirs: src/main
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - Cabal >= 1.18.1.5
      - base >=4.7 && < 5
      - bytestring >= 0.10.4.0
      - containers >= 0.5.5.1
      - directory
      - filelock >= 0.1.0.1
      - filepath
      - http-client
      - lifted-base
      - microlens >= 0.3.0.0
      - monad-control
      - monad-logger >= 0.3.13.1
      - mtl >= 2.1.3.1
      - optparse-applicative >= 0.11.0.2 && < 0.13
      - path
      - path-io >= 0.3.1
      - stack
      - text >= 1.2.0.4
      - transformers
    when:
      - condition: flag(static)
        ld-options: -static -pthread
      - condition: "!flag(disable-git-info)"
        cpp-options: -DUSE_GIT_INFO
        dependencies:
          - gitrev >= 1.1 && < 1.3
          - optparse-simple >= 0.0.3

tests:
  stack-test:
    source-dirs: src/test
    main: Test.hs
    ghc-options: -threaded
    dependencies:
      - Cabal >= 1.18.1.5
      - QuickCheck
      - attoparsec < 0.14
      - base >=4.7 && <5
      - conduit
      - conduit-extra
      - containers >= 0.5.5.1
      - cryptohash
      - directory
      - exceptions
      - hspec <2.3
      - http-conduit
      - monad-logger
      - path
      - path-io >= 0.3.1
      - resourcet
      - retry >= 0.6 && < 0.8
      - stack
      - temporary
      - text
      - transformers

  stack-integration-test:
    source-dirs:
      - test/integration

      # This isn't actually needed to build stack-integration-test, but it
      # makes it easier to load up an individual integration test into stack
      # ghci. It's still a little involved:
      #
      # stack exec -- stack ghci stack:stack-integration-test --flag stack:integration-tests --no-build
      #
      # Then, in ghci:
      #
      # :cd test/integration/tests/.../files
      # :load ../Main.hs
      # main
      - test/integration/lib

    main: IntegrationSpec.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - async < 2.2
      - base >= 4.7 && < 5
      - bytestring
      - conduit
      - conduit-extra
      - containers >= 0.5.5.1
      - directory
      - filepath
      - hspec < 2.3
      - process
      - resourcet
      - temporary
      - text
      - transformers
      - unix-compat
    when:
      condition: "!flag(integration-tests)"
      buildable: no
