resolver: lts-6.14
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- th-utilities-0.2.0.1
- store-0.2.1.2
- store-core-0.2.0.2
- th-orphans-0.13.1
- http-client-0.5.3.1
- http-client-tls-0.3.3
- http-conduit-2.2.0
- optparse-applicative-0.13.0.0
- text-metrics-0.1.0
- pid1-0.1.0.0
flags:
  stack:
    hide-dependency-versions: true
