resolver: lts-9.14
packages:
- .
- location:
    archive: https://github.com/haskell/hackage-security/archive/3297b0f3f4285cb30321baaa7b54e3d22e1f6bd7.tar.gz
    subdirs:
    - hackage-security
  extra-dep: true
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
  mintty:
    win32-2-5: false
extra-deps:
- Cabal-2.0.1.0
- mintty-0.1.1
- bindings-uname-0.1
- path-0.6.1
- path-io-1.3.3
- extra-1.6
- hsc2hs-0.68.2
- hpack-0.20.0
- unliftio-0.2.1.0
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- smallcheck-1.1.3
