resolver: lts-3.19
image:
  containers:
    - base: "fpco/ubuntu-with-libgmp:14.04"
      entrypoints:
        - stack

nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib

extra-deps:
  - open-browser-0.2.1.0
