resolver: lts-11.5

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- rio-0.1.0.0@rev:0
- Cabal-2.2.0.1@rev:0
- hpack-0.28.2
- http-api-data-0.3.8.1@rev:0

# Avoid https://github.com/commercialhaskell/stack/issues/3922
# (triggered because later versions of persistent transitively depends
# on haskell-src-exts, which needs the 'happy' build tool)
- persistent-2.7.1@rev:0
- persistent-sqlite-2.6.4@rev:0
- resourcet-1.1.11@rev:0
- conduit-1.2.13@rev:0
- conduit-extra-1.2.3.2@rev:0
