resolver: lts-9.14
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- Cabal-2.0.1.0
- mintty-0.1.1
- bindings-uname-0.1
- path-0.6.1
- path-io-1.3.3
- extra-1.6
- hsc2hs-0.68.2
- hpack-0.20.0
- unliftio-0.2.1.0
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.1
- smallcheck-1.1.3
