resolver: lts-11.22

packages:
- .

# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
extra-deps:
- Cabal-2.4.0.1@rev:0
- cabal-install-2.4.0.0@rev:1
- resolv-0.1.1.2@rev:0
- infer-license-0.2.0@rev:0 #for hpack-0.31
- hpack-0.31.1@rev:0
- http-api-data-0.3.8.1@rev:1
- githash-0.1.3.0@rev:0
- yaml-0.10.4.0@rev:0 #for hpack-0.31
- windns-0.1.0.0@rev:0
- hackage-security-0.5.3.0@rev:2
- cabal-doctest-1.0.6@rev:2

# Avoid https://github.com/commercialhaskell/stack/issues/4125
# (triggered because later versions of persistent transitively depends
# on haskell-src-exts, which needs the 'happy' build tool)
# THIS IS FIXED AS OF STACK 1.8, but keep these here until next major
# version to maintain the ability to build stack with older versions.
- persistent-2.7.1@rev:0
- persistent-sqlite-2.6.4@rev:0
- resourcet-1.1.11@rev:0
- conduit-1.2.13.1@rev:0
- conduit-extra-1.2.3.2@rev:0

ghc-options:
   "$locals": -fhide-source-paths
