resolver: lts-6.30
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- Cabal-1.24.2.0
- th-utilities-0.2.0.1
- store-0.4.1
- store-core-0.4
- th-orphans-0.13.1
- http-client-0.5.3.3
- http-client-tls-0.3.4
- http-conduit-2.2.3
- optparse-applicative-0.13.0.0
- text-metrics-0.1.0
- pid1-0.1.0.0
- aeson-1.0.2.1
- hpack-0.17.0
- persistent-2.6
- persistent-template-2.5.1.6
- persistent-sqlite-2.6
- cryptohash-sha256-0.11.100.1
- ed25519-0.0.5.0
- hackage-security-0.5.2.2
flags:
  stack:
    hide-dependency-versions: true
