resolver: lts-6.0
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
extra-deps:
- th-lift-instances-0.1.7
- th-utilities-0.1.1.0
- store-0.1.0.1
- th-orphans-0.13.1
- Cabal-1.24.0.0
