snapshot: lts-23.14 # GHC 9.8.4

extra-deps:
# lts-23.14 provides hpack-0.37.0
- hpack-0.38.0
- Cabal-syntax-3.14.1.0
- Cabal-3.14.1.1

docker:
  enable: false
  repo: quay.io/benz0li/ghc-musl:9.8.4

nix:
  # --nix on the command-line to enable.
  packages:
  - zlib
  - unzip

flags:
  stack:
    developer-mode: true
