resolver: lts-8.22
# docker:
#   enable: true
#   repo: fpco/stack-full
# image:
#   containers:
#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
#       name: "fpco/stack-test"
nix:
  # --nix on the command-line to enable.
  enable: false
  packages:
    - zlib
flags:
  stack:
    hide-dependency-versions: true
  mintty:
    win32-2-5: false
extra-deps:
- mintty-0.1.1
- text-metrics-0.3.0
- unicode-transforms-0.3.2
- unliftio-core-0.1.0.0
- unliftio-0.1.0.0
- hpack-0.18.1
