resolver: lts-14.27

packages:
- .

docker:
  enable: false

  #image: fpco/alpine-haskell-stack:8.6.5
  image: fpco/alpine-haskell-stack@sha256:49e7e15f3b1d3f882ba5bb701463b1d508fbf40e5aafce6ea31acd210da570ba

nix:
  # --nix on the command-line to enable.
  packages:
    - zlib
    - unzip
flags:
  stack:
    hide-dependency-versions: true
    supported-build: true
    developer-mode: true

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:
- Cabal-3.0.0.0@rev:0
- hpack-0.33.0@rev:0
- http-download-0.2.0.0@rev:0
- filelock-0.1.1.5@rev:0
- rio-0.1.19.0@rev:0
- rio-prettyprint-0.1.1.0@rev:0
- casa-client-0.0.1@rev:0
- casa-types-0.0.1@rev:0
- pantry-0.5.1.3@rev:0

drop-packages:
# See https://github.com/commercialhaskell/stack/pull/4712
- cabal-install
