Vagrant.configure(2) do |config|
  config.vm.box = "maier/alpine-3.4-x86_64"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z", "--copy-links"], rsync__rsync_path: "/usr/bin/rsync", rsync__chown: false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    echo "https://s3-us-west-2.amazonaws.com/alpine-ghc/7.10" |sudo tee -a /etc/apk/repositories
    curl -o /etc/apk/keys/mitch.tishmack@gmail.com-55881c97.rsa.pub https://raw.githubusercontent.com/mitchty/alpine-ghc/master/mitch.tishmack%40gmail.com-55881c97.rsa.pub
    apk -q update
    apk add alpine-sdk linux-headers musl-dev gmp-dev zlib-dev ghc git rsync gnupg
    cp /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtbeginT.o /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtbeginT.o.orig
    cp /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtbeginS.o /usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/crtbeginT.o
    curl -sSLo /usr/local/bin/stack https://download.fpcomplete.com/temp/manny/stack-alpine-static
    chmod a+x /usr/local/bin/stack
    chown vagrant:vagrant /vagrant
  SHELL
end
