# This is the complex Azure configuration, which is intended for use
# on open source libraries which need compatibility across multiple GHC
# versions, must work with cabal-install, and should be
# cross-platform. For more information and other options, see:
#
# https://docs.haskellstack.org/en/stable/azure_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named azure-pipelines.yml
#
# For better organization, you split various jobs into seprate parts
# and each of them are controlled via individual file.
jobs:
- template: azure-linux-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest
    os: linux

- template: azure-osx-template.yml
  parameters:
    name: macOS
    vmImage: macOS-latest
    os: osx

- template: azure-windows-template.yml
  parameters:
   name: Windows
   vmImage: windows-latest
   os: windows
