name: stack-scripts
version: '0.0.0.0'
author: Emanuel Borsboom
maintainer: manny@fpcomplete.com
license: BSD3
extra-source-files:
- README.md
dependencies:
- base >=4.8 && <5.0
- Cabal
- aeson
- bytestring
- case-insensitive
- conduit
- conduit-combinators
- directory
- extra
- http-conduit
- http-types
- mime-types
- process
- resourcet
- shake
- tar
- text
- zip-archive
- zlib
executables:
  stack-release-script:
    main: release.hs
