# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.6-i386"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__exclude: [".stack_work/", "_release/"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    yum update
    yum -y install perl make automake gcc gmp-devel zlib-devel tar which git xz ncurses-devel
    curl -sSL $(curl -sSL https://api.github.com/repos/commercialhaskell/stack/releases/latest \
                  | grep '"browser_download_url": ".*/stack-.*-i386-linux-gmp4.tar.gz"' \
                  | sed 's/.*"\(.*\)"$/\1/') \
      | tar xzvf - --wildcards --strip-components=1 -C /usr/local/bin '*/stack'
    chmod a+x /usr/local/bin/stack
    if ! which cabal; then
      pushd /vagrant
      stack --install-ghc install cabal-install
      cp `stack exec which cabal` /usr/local/bin/cabal
      popd
    fi
  SHELL
end
