# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.6-i386"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__exclude: [".stack_work/", "_release/"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    yum -y install perl make automake gcc gmp-devel zlib-devel tar which git xz
    if ! which stack; then
      #XXX TEST
      curl -sSL $(curl -sSL https://api.github.com/repos/commercialhaskell/stack/releases/latest \
               |grep '"browser_download_url": ".*/stack-[0-9\\.]\\+-i386-linux-gmp4.gz"' \
               |sed 's/.*"\\(.*\\)"$/\\1/') \
        | gzip -dc \
        >/usr/local/bin/stack
      chmod a+x /usr/local/bin/stack
    fi
    if ! which cabal; then
      pushd /vagrant
      stack --install-ghc install cabal-install
      cp `stack exec which cabal` /usr/local/bin/cabal
      popd
    fi
  SHELL
end
