Vagrant.configure(2) do |config|
  config.vm.box = "kaorimatz/openbsd-5.9-amd64"
  config.vm.synced_folder ENV['STACK_BUILD_DIR'], "/vagrant-build", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.ssh.forward_agent = true
  config.ssh.shell = "/bin/sh"
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    pkg_add xz bzip2 gmp libffi gmake git awscli gnupg-1.4.19p0

    #TODO: use a newer version of stack that supports `stack setup` on OpenBSD for bootstrap
    curl -sSL https://download.fpcomplete.com/dev-tools/stack/stack-1.1.3.20160521-openbsd.gz \
      | gzip -dc > /usr/local/bin/stack
    chmod a+x /usr/local/bin/stack

    #TODO: don't manually install GHC once `stack setup` works (see above)
    if ! which ghc-8.0.1; then
        cd /var/tmp
        curl -sSL https://github.com/commercialhaskell/ghc/releases/download/ghc-8.0.1-release/ghc-8.0.1-x86_64-unknown-openbsd5.9.tar.xz \
          | xzcat  | (tar xf - || true)
        cd ghc-8.0.1
        ./configure --prefix=/usr/local
        gmake install
        cd ..
        rm -rf ghc-8.0.1
    fi

  SHELL
end
