# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "chef/debian-7.8"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__exclude: [".stack_work/", "_release/"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y net-tools wget zlib1g-dev ruby-dev libgmp-dev lsb-release ca-certificates
    if ! which stack; then
      wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | apt-key add -
      echo "deb http://download.fpcomplete.com/debian/$(lsb_release -cs) stable main" >/etc/apt/sources.list.d/fpco.list
      apt-get update
      apt-get install -y stack
    fi
    if ! which cabal; then
      stack --install-ghc build cabal-install
      sudo cp `stack exec which cabal` /usr/local/bin/cabal
    fi
    if ! which fpm; then
        apt-get install -y ruby-dev libffi-dev make build-essential
        apt-get install -y rubygems || true
        gem install fpm --version '< 1.4.0'
    fi
    if ! which deb-s3; then
        gem install deb-s3
    fi
    if ! which aws; then
        apt-get install -y python2.7
        curl -O https://bootstrap.pypa.io/get-pip.py
        python27 get-pip.py
        pip install awscli
    fi
  SHELL
end
