# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "puppetlabs/debian-7.8-64-nocm"
  config.vm.synced_folder ENV['STACK_BUILD_DIR'], "/vagrant-build", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y net-tools wget zlib1g-dev ruby-dev libgmp-dev lsb-release ca-certificates libtinfo-dev
    if ! which stack; then
      wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | apt-key add -
      echo "deb http://download.fpcomplete.com/debian/$(lsb_release -cs) stable main" >/etc/apt/sources.list.d/fpco.list
      apt-get update
    fi
    apt-get install -y stack
    if ! which fpm; then
        apt-get install -y ruby-dev libffi-dev make build-essential
        apt-get install -y rubygems || true
        gem install json --version '< 1.8.0'
        gem install fpm --version '< 1.4.0'
    fi
    if ! which deb-s3; then
        gem install deb-s3
    fi
    if ! which aws; then
        apt-get install -y python2.7
        curl -O https://bootstrap.pypa.io/get-pip.py
        sudo python2.7 get-pip.py
        sudo pip install awscli
    fi
  SHELL
end
