name:        pantry
version:     0.1.0.0
synopsis:    Content addressable Haskell package management
description: Please see the README and documentation at <https://www.stackage.org/package/pantry>
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2019 FP Complete
license:     MIT
github:      commercialhaskell/pantry # TODO move to this repo!

default-extensions:
- MonadFailDesugaring

extra-source-files:
- README.md
- ChangeLog.md
- attic/package-0.1.2.3.tar.gz

dependencies:
- base
- ansi-terminal >= 0.8.1
- digest
- rio
- aeson
- text
- unordered-containers
- containers
- path
- transformers
- generic-deriving
- unliftio
- http-conduit
- http-client-tls
- http-download
- http-types
- http-client
- conduit
- bytestring
- network-uri
- hackage-security
- primitive
- vector
- memory
- cryptonite
- cryptonite-conduit
- persistent
- persistent-sqlite >= 2.8.2
- persistent-template
- resource-pool
- Cabal >= 2.4
- path-io
- rio-orphans
- conduit-extra
- tar-conduit >= 0.3.0
- time
- unix-compat
- hpack >= 0.29.6
- yaml
- zip-archive
- text-metrics
- resourcet
- rio-prettyprint
- mtl

# FIXME remove when we drop store
- integer-gmp
- ghc-prim
- template-haskell
- network
- th-utilities
- th-reify-many
- th-lift
- th-lift-instances
- mono-traversable
- safe
- contravariant
- syb
- deepseq
- array
- hashable
- base-orphans
- th-orphans
- cryptonite
- base64-bytestring
- directory
- filepath

library:
  source-dirs: src/
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: src/windows/
    else:
      source-dirs: src/unix/

  exposed-modules:
  - Pantry
  - Pantry.SHA256
  - Pantry.HPack
  - Pantry.SQLite

  # For testing
  - Pantry.Internal
  - Pantry.Internal.StaticBytes

  # FIXME must be removed from pantry!
  - Data.Aeson.Extended

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - pantry
    - hspec
    - exceptions
    - hedgehog
    - QuickCheck
