Vagrant.configure(2) do |config|
  config.vm.box = "wholebits/arch-64"
  #@@@ config.vm.synced_folder ENV['STACK_BUILD_DIR'], "/vagrant-build", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  #@@@ config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    pacman --noconfirm -Syu ghc happy alex git automake autoconf libtool gcc make perl python python-sphinx docbook-utils patch file bzip2 xz cabal-install
  SHELL
end
