name:    curator
version: 2.0.0.0

ghc-options:
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

dependencies:
- base
- rio
- pantry
- yaml
- path-io
- rio-prettyprint

library:
  source-dirs: src
  exposed-modules:
  - Curator
  dependencies:
  - Cabal
  - bytestring
  - http-client
  - http-client-tls
  - path

executables:
  curator:
    source-dirs: app
    main: Main.hs
    dependencies:
    - curator
    - optparse-applicative
