# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "chef/centos-6.6"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__exclude: [".stack_work/", "_release/"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.ssh.forward_agent = true
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    export PATH=/usr/local/bin:$PATH
    yup update
    yum -y install epel-release
    yum -y install perl make automake gcc gmp-devel zlib-devel rpm-build tar which git xz python-boto deltarpm python-deltarpm rpm-build rpm-sign ncurses-devel
    if ! which stack; then
      curl -sSL https://s3.amazonaws.com/download.fpcomplete.com/centos/6/fpco.repo >/etc/yum.repos.d/fpco.repo
      yum update
    fi
    yum -y install stack
    if ! which cabal; then
      stack --install-ghc build cabal-install
      cp `stack exec which cabal` /usr/local/bin/cabal
    fi
    if ! which fpm; then
        yum -y install ruby-devel
        yum -y install rubygems
        gem install fpm --version '< 1.4.0'
    fi
    if ! [[ -d /opt/rpm-s3 ]]; then
      mkdir -p /opt
      git clone https://github.com/crohr/rpm-s3 /opt/rpm-s3
      (cd /opt/rpm-s3; git submodule update --init)
      echo 'export PATH="/opt/rpm-s3/bin:$PATH"' >/etc/profile.d/rpm-s3.sh
    fi
  SHELL
end
