name: Integration tests

on:
  pull_request:
  push:
    branches:
    - master
    - stable
    - rc/**
    tags:
    - '**'
  workflow_dispatch:

# Stack will use the value of the GH_TOKEN environment variable to authenticate
# its requests of the GitHub REST API, providing a higher request rate limit.
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# As of 26 December 2022, ubuntu-latest, windows-latest and macos-latest come
# with Stack 2.9.1. ubuntu-latest and macos-latest come with GHC 9.4.3.
# windows-latest comes with GHC 9.4.2. windows-latest comes with NSIS 3.08, for
# which the default value of the 'Unicode' installer attribute is 'true'.

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          release-args: "--alpine"
          cache-bust: ""
        - os: windows-latest
          release-args: ""
          cache-bust: "13"
        - os: macos-latest
          release-args: ""
          cache-bust: "23"
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ matrix.cache-bust }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}-${{ matrix.cache-bust }}

    # Separating out Unix-like OS from Windows because of the problem of
    # upgrading GitHub-supplied Stack 2.9.1 to 2.9.3 on Windows
    - name: Install deps and run checks on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      shell: bash
      run: |
        set -ex

        # Stack 2.9.3 is required to build Stack.
        stack upgrade

        # Check the Stack version
        stack --version

        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]
        then
          # Retry installing nix due to nondeterministic error
          #   Fatal error: glibc detected an invalid stdio handle
          # See:
          #   https://github.com/nh2/static-haskell-nix/pull/27#issuecomment-502652181
          #   https://github.com/NixOS/nix/issues/2733
          (for i in {1..5}; do bash <(curl -sSL https://nixos.org/nix/install) --no-daemon && exit 0; done; exit 1)
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix-channel --add https://nixos.org/channels/nixos-22.05 nixpkgs
          nix-channel --update # Get GHC 8.2.2
        fi

        if [[ "${{ matrix.release-args }}" == "--alpine" ]]
        then
            mkdir -p ~/.stack
            touch ~/.stack/config.yaml
            cat > ~/.stack/config.yaml <<EOF
            extra-include-dirs:
            - /usr/include
            extra-lib-dirs:
            - /lib
            - /usr/lib
        EOF
        fi

        # In case GHCup hooks have been created, remove them
        if [ -d $(stack path --stack-root)/hooks ]
        then
            rm -Rf $(stack path --stack-root)/hooks
        fi

        # Do this in the same step as installing deps to get relevant env var modifications
        stack etc/scripts/release.hs check ${{ matrix.release-args }}

        set +ex

    # Separating out Windows because of the problem of upgrading GitHub-supplied
    # Stack 2.9.1 to 2.9.3 on Windows
    - name: Install deps and run checks on Windows
      if: startsWith(runner.os, 'Windows')
      shell: bash
      run: |
        set -ex

        # Stack 2.9.3 is required to build Stack. The --local-bin-path is
        # required to allow Stack (effectively) to overwrite the currently
        # running Stack executable. The should be fixed in later versions of
        # Stack that reflect
        # https://github.com/commercialhaskell/stack/pull/6023
        stack --local-bin-path /c/hostedtoolcache/windows/stack/2.9.1/x64 upgrade

        # Check the Stack version
        stack --version

        # In case GHCup hooks have been created, remove them
        if [ -d $(stack path --stack-root)/hooks ]
        then
            rm -Rf $(stack path --stack-root)/hooks
        fi

        # Do this in the same step as installing deps to get relevant env var modifications
        stack etc/scripts/release.hs check ${{ matrix.release-args }}

        set +ex

    - name: Build bindist
      shell: bash
      run: |
        stack etc/scripts/release.hs build ${{ matrix.release-args }}

    - name: Upload bindist
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}
        path: _release/stack-*

  configuration:
    name: Check for self-hosted runners
    runs-on: ubuntu-latest
    env:
      CAN_SIGN: ${{ secrets.RELEASE_SIGNING_KEY != '' }}
    outputs:
      arm64-runner: ${{ steps.runners.outputs.arm64 }}
      can-sign: ${{ env.CAN_SIGN }}
      test-arm64: ${{ steps.runners.outputs.test-arm64 }}
    steps:
    - name: Check for hosted runners
      id: runners
      shell: bash
      env:
        SELF_HOSTED_RUNNERS: ${{ secrets.SELF_HOSTED_RUNNERS || (github.repository_owner == 'commercialhaskell' && 'arm64') }}
      run: |
        echo "::set-output name=runners::$SELF_HOSTED_RUNNERS"
        if echo "$SELF_HOSTED_RUNNERS" | grep -q 'arm64'; then
          echo "::set-output name=arm64::['self-hosted', 'linux', 'ARM64']"
          echo ::set-output name=test-arm64::true
        else
          echo "::set-output name=arm64::'ubuntu-latest'"
          echo ::set-output name=test-arm64::false
        fi

  linux-arm64:
    name: Linux ARM64
    runs-on: ${{ fromJSON(needs.configuration.outputs.arm64-runner) }}
    needs: configuration
    steps:
    - name: Skipping ARM64
      if: needs.configuration.outputs.test-arm64 == 'false'
      shell: bash
      run: |
        echo '::notice title=ARM64 skipped::To build ARM64, a self-hosted runner needs to be configured and the SELF_HOSTED_RUNNERS secret must contain arm64'

    - name: Clone project
      if: needs.configuration.outputs.test-arm64 == 'true'
      uses: actions/checkout@v3

    - name: Build bindist
      if: needs.configuration.outputs.test-arm64 == 'true'
      shell: bash
      run: |
        set -ex
        docker build . -f etc/dockerfiles/arm64.Dockerfile -t stack --build-arg USERID=$(id -u) --build-arg GROUPID=$(id -g)
        rm -rf _release
        mkdir -p _release
        docker run --rm -v $(pwd):/src -w /src stack bash -c "/home/stack/release build"

    - name: Upload bindist
      if: needs.configuration.outputs.test-arm64 == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: Linux-ARM64
        path: _release/stack-*

  github-release:
    name: Create GitHub release
    permissions:
      contents: write
    needs:
    - configuration
    - integration-tests
    - linux-arm64
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v3
      with:
        name: Linux
        path: _release
    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: macOS
        path: _release
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: Windows
        path: _release
    - name: Download Linux-ARM64 artifact
      if: needs.configuration.outputs.test-arm64 == 'true'
      uses: actions/download-artifact@v3
      with:
        name: Linux-ARM64
        path: _release
    - name: Hash and sign assets
      if: needs.configuration.outputs.can-sign == 'true'
      shell: bash
      env:
        RELEASE_SIGNING_KEY: ${{ secrets.RELEASE_SIGNING_KEY }}
      run: |
        set -e
        echo "$RELEASE_SIGNING_KEY"|gpg --import
        cd _release
        for asset in *; do
          shasum -a 256 "$asset" >"$asset.sha256"
          gpg --digest-algo=sha512 --detach-sig --armor -u 0x575159689BEFB442 "$asset"
        done
    - name: Create GitHub release (final)
      id: github_release_final
      if: "!startsWith(github.ref, 'refs/tags/rc/')"
      uses: ncipollo/release-action@v1.10.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          See https://haskellstack.org/ for installation and upgrade instructions.

          **Changes since v[INSERT PREVIOUS VERSION]:**

          [INSERT CHANGELOG]

          **Thanks to all our contributors for this release:**

          [INSERT CONTRIBUTORS]
        draft: true
        prerelease: false
    - name: Create GitHub release (release candidate)
      id: github_release_rc
      if: "startsWith(github.ref, 'refs/tags/rc/')"
      uses: ncipollo/release-action@v1.10.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: |
          **Changes since v[INSERT PREVIOUS VERSION]:**

          [INSERT CHANGELOG]
        draft: true
        prerelease: true
    - name: Upload assets to GitHub release (final)
      if: "!startsWith(github.ref, 'refs/tags/rc/')"
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "_release/*"
        draft: true
        prerelease: false
        overwrite: true
        release_id: ${{ steps.github_release_final.outputs.id }}
    - name: Upload assets to GitHub release (release candidate)
      if: "startsWith(github.ref, 'refs/tags/rc/')"
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "_release/*"
        draft: true
        prerelease: true
        overwrite: true
        release_id: ${{ steps.github_release_rc.outputs.id }}
