name: Linting

on:
  pull_request:
  push:
    branches:
    - master
    - stable
    - rc/**

jobs:
  style:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Clone project
      uses: actions/checkout@v4
    - name: Apply yamllint
      uses: ibiqlik/action-yamllint@v3
      with:
        format: github
    - name: Set up HLint
      uses: haskell-actions/hlint-setup@v2
      with:
        version: "3.8"
    - name: Apply HLint
      run: |
        set -ex
        hlint app/
        hlint src/
        hlint --hint=.hlint-test.yaml tests/unit
        hlint --hint=.hlint-test.yaml tests/integration
