Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-10.3-RELEASE"
  config.vm.synced_folder "../../..", "/vagrant", type: "rsync", rsync__verbose: true, rsync__exclude: [".stack-work/", "_release/", ".cabal-sandbox/", "cabal.sandbox.config", "dist/", ".#*#"], rsync__args: ["--verbose", "--archive", "--delete", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.ssh.forward_agent = true
  config.ssh.shell = "/bin/sh"
  config.vm.provision "shell", inline: <<-SHELL
    set -xe
    if ! which stack; then
      mkdir -p /usr/local/etc/pkg/repos
      cd /usr/local/etc/pkg/repos
      fetch --no-verify-peer --no-verify-hostname https://stack-pkg.applicative.tech/stack-pkg-applicative-tech.conf
      fetch --no-verify-peer --no-verify-hostname https://stack-pkg.applicative.tech/stack-pkg-applicative-tech.pub
      pkg update
    fi
    pkg install -y stack ca_root_nss gmake awscli git gnupg
  SHELL
end
